### ISSUE TITLE
47-bit address restriction, lightuserdata and arm64

### ISSUE THREAD

**Issue by vielmetti** [openresty/luajit2#24]
The mainline LuaJIT has a proposal to support enhancements to lightuserdata to handle the `arm64` architecture which has 48-bit addresses. The lengthy discussion is at https://github.com/LuaJIT/LuaJIT/issues/49 and there is a PR at https://github.com/LuaJIT/LuaJIT/pull/230 which is labelled "wontfix".

Is the OpenResty LuaJIT community amenable to reopening this issue? If so, I'm happy to address this issue with downstream projects that are affected by it.

**Comment by agentzh** [comment]
@vielmetti Seems like you misread those threads? The LuaJIT author actually suggested avoiding lightuserdata instead of enhancing it.

Right now we have some corporate sponsors to sponsor the "no lightud" work on the open source OpenResty core and we are already working on it and it's expected to be out around late July (yeah, one month to go :))

**Comment by vielmetti** [comment]
Doing "no lightud" would be terrific for OpenResty, and that addresses the immediate concern. Thanks for the update.

**Comment by khasim** [comment]
@agentzh Hi, I am trying to evaluate Kong for ARMv8, which needs OpenResty with LuaJIT. If you don't mind can you please update on the lightud work ? Do we need to wait for the official OpenResty release to test this out ? Thanks.

**Comment by khasim** [comment]
@agentzh @tianon Hi,

Can you please guide me on how to proceed further on this topic, I am mainly looking at getting Kong supported on ARMv8, which inturn is depending on OpenResty for ARMv8. 

Thanks.
