### ISSUE TITLE
symbol lookup error: undefined symbol: lua_setexdata

### ISSUE THREAD

**Issue by sunnybear** [openresty/luajit2#34]
Build nginx with openresty-lua module + openresty-luajit, get the following errors in logs (not sure, safe them are or not). Building with stack LuaJIT doesn't give such errors

**Comment by agentzh** [comment]
@sunnybear Your nginx process loads the wrong libluajit-5.1.so at runtime. This is also why it is recommended to use OpenResty directly. Set your rpath or /etc/ld.so.conf to make your nginx find the right libluajit-5.1.so.

**Comment by agentzh** [comment]
Or set the `LD_LIBRARY_PATH` env (not recommended though).

**Comment by sunnybear** [comment]
With right LuaJIT it causes generic fault with ssl functions. Maybe additional docs from your side - how to compile Openresty Lua + Openresty LuaJIT - is required.

Openresty nginx build is too heavy for us and doesn't cover all functions, so we use custom build.

**Comment by agentzh** [comment]
@sunnybear You should first try if OpenResty works for you. Then you can check how OpenResty handle things. It's open source. Documentation is already well written here for custom build:

https://github.com/openresty/lua-nginx-module#installation

Average users may get into some pitfalls. That's why we created OpenResty in the first place. BTW, you can always add new libraries and new nginx C modules as well as removing unneeded ones when using OpenResty. Just check out the output of the `./configure --help` command of OpenResty. It's just like NGINX's build system. What you're saying may just be your own false imagination...Just my 2 cents.

**Comment by sunnybear** [comment]
thank youm but we dont need to use OpenResty :)
