### ISSUE TITLE
something is wrong when using tostring method with big number

### ISSUE THREAD

**Issue by theoneqq** [openresty/luajit2#48]
luajit2/src/host/minlua.c:145
`#define lua_number2str(s,n)sprintf((s),"%.14g",(n))`

As illustrate blow, it makes number bigger than 10e14 to string in scientific notation format.
however, if we use the result as a parameter to call hincrby method of redis, it will cause a error, namely, the value is not a number of out of range

**Comment by agentzh** [comment]
10^14 already exceeds a 32-bit integer's range and LuaJIT will store it as a double-precision floating point number. You need 64-bit integers, in LuaJIT, should use cdata instead. Like this:

```
$ resty -e 'print(1234567901234567890LL)'
1234567901234567890LL
```

Or to remove the `LL` suffix:

```
$ resty -e 'print(string.sub(tostring(1234567901234567890LL), 0, -3))'
1234567901234567890
```

If you do no want to do arithmetic on the 64-bit integer values, then you should just use strings from the very beginning instead of using Lua numbers or Lua cdata objects.

BTW, the code you quoted is from `minilua` (you have a type in your message, not `minlua`). The minilua is only used when building the LuaJIT itself. It no longer exists in the final installed LuaJIT tree.

**Comment by theoneqq** [comment]
openresty/bundle/lua-resty-redis/lib/resty/redis.lua
```
local function _gen_req(args)
    local nargs = #args

    local req = new_tab(nargs * 5 + 1, 0)
    req[1] = "*" .. nargs .. "\r\n"
    local nbits = 2

    for i = 1, nargs do
        local arg = args[i]
        if type(arg) ~= "string" then
            arg = tostring(arg)
        end

        req[nbits] = "$"
        req[nbits + 1] = #arg
        req[nbits + 2] = "\r\n"
        req[nbits + 3] = arg
        req[nbits + 4] = "\r\n"

        nbits = nbits + 5
    end

    -- it is much faster to do string concatenation on the C land
    -- in real world (large number of strings in the Lua VM)
    return req
end
```
Thanks, I got it. I wander if I can modify above tostring method, instead of to distinguish common number and big number.

**Comment by agentzh** [comment]
@theoneqq Better not in that redis library. It might be a good idea to simply change the LuaJIT's `tostring()` method. The `LL` suffix is indeed not very helpful usually.

**Comment by theoneqq** [comment]
It's really a good idea, I will try
