### ISSUE TITLE
Wrong GC64 build flag for travis

### ISSUE THREAD

**Issue by exjesper** [openresty/luajit2#85]
I believe this should be `-DLUAJIT_ENABLE_GC64` not `-DLUAJIT_USE_GC64`

https://github.com/openresty/luajit2/blob/9d5750d28478abfdcaefdfdc408f87752a21e431/.travis.yml#L38

**Comment by thibaultcha** [comment]
Hi,

Nice catch, thank you. Since GC64 is now enabled by default with https://github.com/openresty/luajit2/commit/bd00094c3b50e193fb32aad79b7ea8ea6b78ed25, I changed the tests matrix to have a non-GC64 mode instead in https://github.com/openresty/luajit2/commit/38cb695de87cfeadcba5eeaf57f39e41d529aa1f.
